### ISSUE TITLE
Incorrect Result for Perfect Primes

### ISSUE THREAD

**Issue by jameelkaisar** [Saqibhussain596/Java-DSA#1]
isPrime(25) returns true

https://github.com/Saqibhussain596/Java-DSA/blob/1dbc391e54072325578f7c9248e8dc6f2b8837a4/01-functions/questions/sol1.java#L11

It should be:
```java
for (int count = 2; count * count <= num; count++) { 
```

**Comment by saqibganaie** [comment]
Oh yeah 😅 .Thanks
